#
# /etc/makepkg.conf - YummyOS makepkg configuration
#

#########################################################################
# ARCHITECTURE, COMPILE FLAGS
#########################################################################
CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

# Compiler flags
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fexceptions -fvisibility=hidden -ffunction-sections -fdata-sections -Wl,-O1 -Wl,--as-needed -Wl,--sort-common -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto"
CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fexceptions -fvisibility=hidden -ffunction-sections -fdata-sections -Wl,-O1 -Wl,--as-needed -Wl,--sort-common -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now,-z,pack-relative-relocs -flto=auto"
LTOFLAGS="-flto=auto"
RUSTFLAGS="-C opt-level=2 -C target-cpu=x86-64-v3"

# Debug flags
DEBUG_CFLAGS="-g -fvar-tracking-assignments -ffile-prefix-map=${startdir}=${DBGSRCDIR:-}"
DEBUG_CXXFLAGS="-g -fvar-tracking-assignments -ffile-prefix-map=${startdir}=${DBGSRCDIR:-}"

# Strip static libraries
BUILDFLAGS=(DEBUG_CFLAGS DEBUG_CXXFLAGS)

# Make Flags
MAKEFLAGS="-j$(nproc)"

# Use distcc for distributed compilation (enable if desired)
#DISTCC_HOSTS=''

#########################################################################
# BUILD OUTPUT
#########################################################################
# Build directory
BUILDDIR=/tmp/makepkg

# Use CCACHE if available
#BUILDENV=(ccache)

#########################################################################
# PACKAGE OUTPUT
#########################################################################
PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.zst'
# COMPRESSZSTD=(zstd -T0 -20)

#########################################################################
# OPTIONS
#########################################################################
# Run the strip command on binaries/libraries
OPTIONS=(strip debug docs libtool emptydirs zipman purge !ccache !check !debugflags)

# File permissions
DIR_PERMISSIONS=755
FILE_PERMISSIONS=644

#########################################################################
# INSTALL SCRIPTS
#########################################################################
# Pre-install script
#PRE_INSTALL=()

# Post-install script
#POST_INSTALL=()

# Compression
COMPRESSGZ=(gzip -c -f -n)
COMPRESSBZ2=(bzip2 -c -f)
COMPRESSXZ=(xz -c -f -T "$(nproc)")
COMPRESSZST=(zstd -c -f -T "$(nproc)" --ultra -20)
COMPRESSLRZ=(lrzip -q)
COMPRESSLZO=(lzop -q)
COMPRESSLZ4=(lz4 -q)
COMPRESSZSTD=(zstd -c -f -T "$(nproc)")

# tar options
TAROPTIONS=('--use-compress-program' 'zstd -T0 --ultra -20')
