# /etc/mkinitcpio.conf - YummyOS mkinitcpio configuration
#
# The mkinitcpio image is required for booting. Modify with care.

MODULES=()
BINARIES=()
FILES=()

# Base hooks for all installs
HOOKS=(base systemd autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)

# Hooks added for specific features
#   plymouth        - graphical boot splash
#   plymouth-encrypt - Plymouth with LUKS support (add if using encryption)
#   lvm2            - LVM support (add if using LVM)
#   mdadm_udev      - Software RAID (add if using RAID)
#   network         - Bring up network in early boot (add for NFS/PXE root)

# Hooks for YummyOS default install
HOOKS=(base systemd autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck plymouth)

#COMPRESSION="zstd"
#COMPRESSION_OPTIONS=(-9)
