#
# /etc/pacman.conf - YummyOS pacman configuration
#

#
# GENERAL OPTIONS
#
[options]
RootDir         = /
DBPath          = /var/lib/pacman/
CacheDir        = /var/cache/pacman/pkg/
GPGDir          = /etc/pacman.d/gnupg/
LogFile         = /var/log/pacman.log
HoldPkg         = pacman glibc
SyncFirst       = pacman
CleanMethod     = KeepInstalled
Architecture    = auto

# Use Color
Color

# Show progress bars
ILoveCandy

# Use parallel downloads (set to number of cores, e.g. 5)
ParallelDownloads = 5

# By default, pacman accepts packages signed by keys that its local keyring
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Misc options
#UseSyslog
#NoProgressBar
CheckSpace
VerbosePkgLists
DualMirrors
ParallelRsync
#Pacaur
#NoPowerDummy
#MoveExistsGroup

#
# REPOSITORIES
#

[yummyos]
Include = /etc/pacman.d/yummyos-mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

# If you want to run 32-bit applications on x86_64, enable the multilib repository.
#[multilib]
#Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# more instructions.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
